### ISSUE TITLE
[CRITICAL] Fairy IntelliJ overrides Minecraft Development's bukkit template

### ISSUE THREAD

**Issue by terminalsin** [FairyProject/fairy-intellij#29]
As the title says, using the bukkit/spigot template in the Minecraft Development plugin outputs Fairy's template as opposed to the regular bukkit template. This is... problematic to say the least. Perhaps try using a different file path to circumvent conflict.

**Comment by LeeGodSRC** [comment]
Fixed in InteliJ plugin 0.3.5
